### ISSUE TITLE
Failed to transform android.jar to match attributes

### ISSUE THREAD

**Issue by KishorJena** [piroposantosdev/react-native-vlc-player#2]
```bash
 What went wrong:
Execution failed for task ':react-native-vlc-media-player:parseDebugLocalResources'.
> Could not resolve all files for configuration ':react-native-vlc-media-player:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: C:\Users\ksrje\AppData\Local\Android\Sdk\platforms\android-28\android.jar
```

**Comment by piroposantosdev** [comment]
try to clear gradle cache before build it... using ./gradlew clean command

**Comment by KishorJena** [comment]
yeah tried that.  still same error.

**Comment by piroposantosdev** [comment]
@CrackerKSR what version of RN you are using? And what Gradle version? Other question, have you follow the android instructions written in main page of project?

**Comment by KishorJena** [comment]
### package.json
```json
...
 "dependencies": {
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-vlc-media-player": "github:piroposantosdev/react-native-vlc-player"
  },
...
```
### gradle of react-nativevlc-player
```groovy
apply plugin: 'com.android.library'
android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters 'armeabi-v7a','x86_64','arm64-v8a','x86'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven {
        url "https://mvnrepository.com/artifact/org.videolan.android"
    }
    google()
    jcenter()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.facebook.react:react-native:+"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'org.videolan.android:libvlc-all:3.1.12'
}
```

### gradle of rootProject
```groovy
import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.1.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}

### gradle of rootProject/app
```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile


project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"


def enableSeparateBuildPerCPUArchitecture = false


def enableProguardInReleaseBuilds = false


def jscFlavor = 'org.webkit:android-jsc:+'


def enableHermes = project.ext.react.get("enableHermes", false);


def reactNativeArchitectures() {
    def value = project.getProperties().get("reactNativeArchitectures")
    return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion
    packagingOptions {

        pickFirst 'lib/x86/libc++_shared.so'

        pickFirst 'lib/arm64-v8a/libc++_shared.so'

        pickFirst 'lib/x86_64/libc++_shared.so'

        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
    defaultConfig {
        multiDexEnabled true
        applicationId "com.rosp3"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()

        if (isNewArchitectureEnabled()) {
            // We configure the NDK build only if you decide to opt-in for the New Architecture.
            externalNativeBuild {
                ndkBuild {
                    arguments "APP_PLATFORM=android-21",
                        "APP_STL=c++_shared",
                        "NDK_TOOLCHAIN_VERSION=clang",
                        "GENERATED_SRC_DIR=$buildDir/generated/source",
                        "PROJECT_BUILD_DIR=$buildDir",
                        "REACT_ANDROID_DIR=$rootDir/../node_modules/react-native/ReactAndroid",
                        "REACT_ANDROID_BUILD_DIR=$rootDir/../node_modules/react-native/ReactAndroid/build",
                        "NODE_MODULES_DIR=$rootDir/../node_modules"
                    cFlags "-Wall", "-Werror", "-fexceptions", "-frtti", "-DWITH_INSPECTOR=1"
                    cppFlags "-std=c++17"
                    // Make sure this target name is the same you specify inside the
                    // src/main/jni/Android.mk file for the `LOCAL_MODULE` variable.
                    targets "rosp3_appmodules"
                }
            }
            if (!enableSeparateBuildPerCPUArchitecture) {
                ndk {
                    abiFilters (*reactNativeArchitectures())
                }
            }
        }
    }

    if (isNewArchitectureEnabled()) {
        // We configure the NDK build only if you decide to opt-in for the New Architecture.
        externalNativeBuild {
            ndkBuild {
                path "$projectDir/src/main/jni/Android.mk"
            }
        }
        def reactAndroidProjectDir = project(':ReactAndroid').projectDir
        def packageReactNdkDebugLibs = tasks.register("packageReactNdkDebugLibs", Copy) {
            dependsOn(":ReactAndroid:packageReactNdkDebugLibsForBuck")
            from("$reactAndroidProjectDir/src/main/jni/prebuilt/lib")
            into("$buildDir/react-ndk/exported")
        }
        def packageReactNdkReleaseLibs = tasks.register("packageReactNdkReleaseLibs", Copy) {
            dependsOn(":ReactAndroid:packageReactNdkReleaseLibsForBuck")
            from("$reactAndroidProjectDir/src/main/jni/prebuilt/lib")
            into("$buildDir/react-ndk/exported")
        }
        afterEvaluate {
            // If you wish to add a custom TurboModule or component locally,
            // you should uncomment this line.
            // preBuild.dependsOn("generateCodegenArtifactsFromSchema")
            preDebugBuild.dependsOn(packageReactNdkDebugLibs)
            preReleaseBuild.dependsOn(packageReactNdkReleaseLibs)

            // Due to a bug inside AGP, we have to explicitly set a dependency
            // between configureNdkBuild* tasks and the preBuild tasks.
            // This can be removed once this is solved: https://issuetracker.google.com/issues/207403732
            configureNdkBuildRelease.dependsOn(preReleaseBuild)
            configureNdkBuildDebug.dependsOn(preDebugBuild)
            reactNativeArchitectures().each { architecture ->
                tasks.findByName("configureNdkBuildDebug[${architecture}]")?.configure {
                    dependsOn("preDebugBuild")
                }
                tasks.findByName("configureNdkBuildRelease[${architecture}]")?.configure {
                    dependsOn("preReleaseBuild")
                }
            }
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include (*reactNativeArchitectures())
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])

    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        //noinspection GradleDynamicVersion
        implementation("com.facebook.react:hermes-engine:+") { // From node_modules
            exclude group:'com.facebook.fbjni'
        }
    } else {
        implementation jscFlavor
    }
}

if (isNewArchitectureEnabled()) {
    // If new architecture is enabled, we let you build RN from source
    // Otherwise we fallback to a prebuilt .aar bundled in the NPM package.
    // This will be applied to all the imported transtitive dependency.
    configurations.all {
        resolutionStrategy.dependencySubstitution {
            substitute(module("com.facebook.react:react-native"))
                    .using(project(":ReactAndroid"))
                    .because("On New Architecture we're building React Native from source")
            substitute(module("com.facebook.react:hermes-engine"))
                    .using(project(":ReactAndroid:hermes-engine"))
                    .because("On New Architecture we're building Hermes from source")
        }
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

def isNewArchitectureEnabled() {
    // To opt-in for the New Architecture, you can either:
    // - Set `newArchEnabled` to true inside the `gradle.properties` file
    // - Invoke gradle with `-newArchEnabled=true`
    // - Set an environment variable `ORG_GRADLE_PROJECT_newArchEnabled=true`
    return project.hasProperty("newArchEnabled") && project.newArchEnabled == "true"
}


```

**Comment by KishorJena** [comment]
> ### package.json
> ```json
> ...
>  "dependencies": {
>     "react": "18.0.0",
>     "react-native": "0.69.5",
>     "react-native-vlc-media-player": "github:piroposantosdev/react-native-vlc-player"
>   },
> ...
> ```
> 
> ### gradle of react-nativevlc-player
> ```groovy
> apply plugin: 'com.android.library'
> android {
>     compileSdkVersion 28
>     buildToolsVersion '28.0.3'
> 
>     defaultConfig {
>         minSdkVersion 17
>         targetSdkVersion 28
>         versionCode 1
>         versionName "1.0"
>         ndk {
>             abiFilters 'armeabi-v7a','x86_64','arm64-v8a','x86'
>         }
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> repositories {
>     maven {
>         url "https://mvnrepository.com/artifact/org.videolan.android"
>     }
>     google()
>     jcenter()
> }
> 
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation "com.facebook.react:react-native:+"
>     implementation 'androidx.legacy:legacy-support-v4:1.0.0'
>     implementation 'org.videolan.android:libvlc-all:3.1.12'
> }
> ```
> 
> ### gradle of rootProject
> ```groovy
> import org.apache.tools.ant.taskdefs.condition.Os
> 
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "31.0.0"
>         minSdkVersion = 21
>         compileSdkVersion = 31
>         targetSdkVersion = 31
> 
>         if (System.properties['os.arch'] == "aarch64") {
>             // For M1 Users we need to use the NDK 24 which added support for aarch64
>             ndkVersion = "24.0.8215888"
>         } else {
>             // Otherwise we default to the side-by-side NDK version from AGP.
>             ndkVersion = "21.4.7075529"
>         }
>     }
>     repositories {
>         google()
>         mavenCentral()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:7.1.1")
>         classpath("com.facebook.react:react-native-gradle-plugin")
>         classpath("de.undercouch:gradle-download-task:5.0.1")
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
>         mavenCentral {
>             // We don't want to fetch react-native from Maven Central as there are
>             // older versions over there.
>             content {
>                 excludeGroup "com.facebook.react"
>             }
>         }
>         google()
>         maven { url 'https://www.jitpack.io' }
>     }
> }
> 
> ### gradle of rootProject/app
> ```groovy
> apply plugin: "com.android.application"
> 
> import com.android.build.OutputFile
> 
> 
> project.ext.react = [
>     enableHermes: false,  // clean and rebuild if changing
> ]
> 
> apply from: "../../node_modules/react-native/react.gradle"
> 
> 
> def enableSeparateBuildPerCPUArchitecture = false
> 
> 
> def enableProguardInReleaseBuilds = false
> 
> 
> def jscFlavor = 'org.webkit:android-jsc:+'
> 
> 
> def enableHermes = project.ext.react.get("enableHermes", false);
> 
> 
> def reactNativeArchitectures() {
>     def value = project.getProperties().get("reactNativeArchitectures")
>     return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
> }
> 
> android {
>     ndkVersion rootProject.ext.ndkVersion
> 
>     compileSdkVersion rootProject.ext.compileSdkVersion
>     packagingOptions {
> 
>         pickFirst 'lib/x86/libc++_shared.so'
> 
>         pickFirst 'lib/arm64-v8a/libc++_shared.so'
> 
>         pickFirst 'lib/x86_64/libc++_shared.so'
> 
>         pickFirst 'lib/armeabi-v7a/libc++_shared.so'
>     }
>     defaultConfig {
>         multiDexEnabled true
>         applicationId "com.rosp3"
>         minSdkVersion rootProject.ext.minSdkVersion
>         targetSdkVersion rootProject.ext.targetSdkVersion
>         versionCode 1
>         versionName "1.0"
>         buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
> 
>         if (isNewArchitectureEnabled()) {
>             // We configure the NDK build only if you decide to opt-in for the New Architecture.
>             externalNativeBuild {
>                 ndkBuild {
>                     arguments "APP_PLATFORM=android-21",
>                         "APP_STL=c++_shared",
>                         "NDK_TOOLCHAIN_VERSION=clang",
>                         "GENERATED_SRC_DIR=$buildDir/generated/source",
>                         "PROJECT_BUILD_DIR=$buildDir",
>                         "REACT_ANDROID_DIR=$rootDir/../node_modules/react-native/ReactAndroid",
>                         "REACT_ANDROID_BUILD_DIR=$rootDir/../node_modules/react-native/ReactAndroid/build",
>                         "NODE_MODULES_DIR=$rootDir/../node_modules"
>                     cFlags "-Wall", "-Werror", "-fexceptions", "-frtti", "-DWITH_INSPECTOR=1"
>                     cppFlags "-std=c++17"
>                     // Make sure this target name is the same you specify inside the
>                     // src/main/jni/Android.mk file for the `LOCAL_MODULE` variable.
>                     targets "rosp3_appmodules"
>                 }
>             }
>             if (!enableSeparateBuildPerCPUArchitecture) {
>                 ndk {
>                     abiFilters (*reactNativeArchitectures())
>                 }
>             }
>         }
>     }
> 
>     if (isNewArchitectureEnabled()) {
>         // We configure the NDK build only if you decide to opt-in for the New Architecture.
>         externalNativeBuild {
>             ndkBuild {
>                 path "$projectDir/src/main/jni/Android.mk"
>             }
>         }
>         def reactAndroidProjectDir = project(':ReactAndroid').projectDir
>         def packageReactNdkDebugLibs = tasks.register("packageReactNdkDebugLibs", Copy) {
>             dependsOn(":ReactAndroid:packageReactNdkDebugLibsForBuck")
>             from("$reactAndroidProjectDir/src/main/jni/prebuilt/lib")
>             into("$buildDir/react-ndk/exported")
>         }
>         def packageReactNdkReleaseLibs = tasks.register("packageReactNdkReleaseLibs", Copy) {
>             dependsOn(":ReactAndroid:packageReactNdkReleaseLibsForBuck")
>             from("$reactAndroidProjectDir/src/main/jni/prebuilt/lib")
>             into("$buildDir/react-ndk/exported")
>         }
>         afterEvaluate {
>             // If you wish to add a custom TurboModule or component locally,
>             // you should uncomment this line.
>             // preBuild.dependsOn("generateCodegenArtifactsFromSchema")
>             preDebugBuild.dependsOn(packageReactNdkDebugLibs)
>             preReleaseBuild.dependsOn(packageReactNdkReleaseLibs)
> 
>             // Due to a bug inside AGP, we have to explicitly set a dependency
>             // between configureNdkBuild* tasks and the preBuild tasks.
>             // This can be removed once this is solved: https://issuetracker.google.com/issues/207403732
>             configureNdkBuildRelease.dependsOn(preReleaseBuild)
>             configureNdkBuildDebug.dependsOn(preDebugBuild)
>             reactNativeArchitectures().each { architecture ->
>                 tasks.findByName("configureNdkBuildDebug[${architecture}]")?.configure {
>                     dependsOn("preDebugBuild")
>                 }
>                 tasks.findByName("configureNdkBuildRelease[${architecture}]")?.configure {
>                     dependsOn("preReleaseBuild")
>                 }
>             }
>         }
>     }
> 
>     splits {
>         abi {
>             reset()
>             enable enableSeparateBuildPerCPUArchitecture
>             universalApk false  // If true, also generate a universal APK
>             include (*reactNativeArchitectures())
>         }
>     }
>     signingConfigs {
>         debug {
>             storeFile file('debug.keystore')
>             storePassword 'android'
>             keyAlias 'androiddebugkey'
>             keyPassword 'android'
>         }
>     }
>     buildTypes {
>         debug {
>             signingConfig signingConfigs.debug
>         }
>         release {
>             // Caution! In production, you need to generate your own keystore file.
>             // see https://reactnative.dev/docs/signed-apk-android.
>             signingConfig signingConfigs.debug
>             minifyEnabled enableProguardInReleaseBuilds
>             proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
>         }
>     }
> 
>     // applicationVariants are e.g. debug, release
>     applicationVariants.all { variant ->
>         variant.outputs.each { output ->
>             // For each separate APK per architecture, set a unique version code as described here:
>             // https://developer.android.com/studio/build/configure-apk-splits.html
>             // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
>             def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
>             def abi = output.getFilter(OutputFile.ABI)
>             if (abi != null) {  // null for the universal-debug, universal-release variants
>                 output.versionCodeOverride =
>                         defaultConfig.versionCode * 1000 + versionCodes.get(abi)
>             }
> 
>         }
>     }
> }
> 
> dependencies {
>     implementation fileTree(dir: "libs", include: ["*.jar"])
> 
>     //noinspection GradleDynamicVersion
>     implementation "com.facebook.react:react-native:+"  // From node_modules
> 
>     implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
> 
>     debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
>         exclude group:'com.facebook.fbjni'
>     }
> 
>     debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
>         exclude group:'com.facebook.flipper'
>         exclude group:'com.squareup.okhttp3', module:'okhttp'
>     }
> 
>     debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
>         exclude group:'com.facebook.flipper'
>     }
> 
>     if (enableHermes) {
>         //noinspection GradleDynamicVersion
>         implementation("com.facebook.react:hermes-engine:+") { // From node_modules
>             exclude group:'com.facebook.fbjni'
>         }
>     } else {
>         implementation jscFlavor
>     }
> }
> 
> if (isNewArchitectureEnabled()) {
>     // If new architecture is enabled, we let you build RN from source
>     // Otherwise we fallback to a prebuilt .aar bundled in the NPM package.
>     // This will be applied to all the imported transtitive dependency.
>     configurations.all {
>         resolutionStrategy.dependencySubstitution {
>             substitute(module("com.facebook.react:react-native"))
>                     .using(project(":ReactAndroid"))
>                     .because("On New Architecture we're building React Native from source")
>             substitute(module("com.facebook.react:hermes-engine"))
>                     .using(project(":ReactAndroid:hermes-engine"))
>                     .because("On New Architecture we're building Hermes from source")
>         }
>     }
> }
> 
> // Run this once to be able to run the application with BUCK
> // puts all compile dependencies into folder libs for BUCK to use
> task copyDownloadableDepsToLibs(type: Copy) {
>     from configurations.implementation
>     into 'libs'
> }
> 
> apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
> 
> def isNewArchitectureEnabled() {
>     // To opt-in for the New Architecture, you can either:
>     // - Set `newArchEnabled` to true inside the `gradle.properties` file
>     // - Invoke gradle with `-newArchEnabled=true`
>     // - Set an environment variable `ORG_GRADLE_PROJECT_newArchEnabled=true`
>     return project.hasProperty("newArchEnabled") && project.newArchEnabled == "true"
> }
> ```

Here are the files. RN 0.69.5.

**Comment by KishorJena** [comment]
Now i am setting RN to exact 0.69.0. last time I simply wrote 0.69 and it installed 0.69.5. I will update if it wroks

**Comment by piroposantosdev** [comment]
i didnt test it, but maybe the problem is that your root gradle is targeting a different sdk from vlc player gradle... try to set your root gradle to target the same sdk version

try changing this:
`buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31` 

to this:
`compileSdkVersion 28
    buildToolsVersion '28.0.3'
 minSdkVersion 17
        targetSdkVersion 28`

try this and let me updated...

**Comment by KishorJena** [comment]
> i didnt test it, but maybe the problem is that your root gradle is targeting a different sdk from vlc player gradle... try to set your root gradle to target the same sdk version
> 
> try changing this: `buildToolsVersion = "31.0.0" minSdkVersion = 21 compileSdkVersion = 31 targetSdkVersion = 31`
> 
> to this: `compileSdkVersion 28 buildToolsVersion '28.0.3' minSdkVersion 17 targetSdkVersion 28`
> 
> try this and let me updated...

Doing so gives another error but this time for project building and its core modules.

**Comment by piroposantosdev** [comment]
which error now?

**Comment by KishorJena** [comment]
> which error now?

```bash
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:

     Dependency 'androidx.appcompat:appcompat:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-28'

     Dependency 'androidx.appcompat:appcompat-resources:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-28'

     Dependency 'androidx.emoji2:emoji2-views-helper:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-28'

     Dependency 'androidx.emoji2:emoji2:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-28'

     Dependency 'androidx.core:core:1.7.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-28'

     Dependency 'androidx.lifecycle:lifecycle-process:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-28'

     Dependency 'androidx.lifecycle:lifecycle-runtime:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-28'
```

## But I match the 'react-native-vlc-player' gradle with root gradle and error gone. !!! 
I will close the issue after testing it once again.

**Comment by piroposantosdev** [comment]
you set vlc gradle to 31? Maybe your environment is only targeting to sdk 31 and it was trying to build using 28 in VLC

**Comment by KishorJena** [comment]
> you set vlc gradle to 31? Maybe your environment is only targeting to sdk 31 and it was trying to build using 28 in VLC

Yes. I did reverse of above solution given by you and it worked.  (Thanks for suggestion)

```gradle
...
 compileSdkVersion 31
    buildToolsVersion '31.0.0'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 31
...
```

Project built without error. Now I need to invoke the component of this vlc module I hope no major error will occure. 🤞
