### ISSUE TITLE
is it work on 0.70.1 farbic mode?

### ISSUE THREAD

**Issue by Yunnathai** [piroposantosdev/react-native-vlc-player#3]
hi. thanks for your work. is it work on 0.70.1 farbic mode?

**Comment by piroposantosdev** [comment]
Sorry, i dont know, i have not test it yet. You can try, and please tell me if it works.

**Comment by Yunnathai** [comment]
i have try it. it doesn't work. how to slove this?

**Comment by piroposantosdev** [comment]
it's hard to say, what error you got?
