### ISSUE TITLE
Not playing any video file.

### ISSUE THREAD

**Issue by KishorJena** [piroposantosdev/react-native-vlc-player#4]
```bash
 LOG  stopped...
 LOG  bufferring...
 LOG  onError... {"currentTime": 0, "duration": 0, "isPlaying": false, "position": 0, "type": "Error"}
```
code:
```js
           <VLCPlayer
        style={{height:200}}
        videoAspectRatio="16:9"
        source={{ uri: RNFS.DownloadDirectoryPath+'/sample1.mkv'}}
        autoplay={true}
        repeat={true}
        onBuffering={()=>{log('bufferring...')}}
        onEnded={()=>{log('onEnded...')}}
        onStopped={()=>{log('stopped...')}}
        onPaused={()=>{log('onPaused...')}}
        onError={(x)=>{log('onError...',x)}}
        
    />
```

**Comment by piroposantosdev** [comment]
use this...
`<VlCPlayerView
          autoplay={false}
          url="https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4"
          Orientation={Orientation}
          ggUrl=""
          showGG={true}
          showTitle={true}
          title="Big Buck Bunny"
          showBack={true}
          onLeftPress={()=>{}}
       />`

VLCPlayer is just for simple usage, there is no configurations for it

**Comment by piroposantosdev** [comment]
did u already test it?

**Comment by KishorJena** [comment]
> did u already test it?

I just started. will updated asap

**Comment by KishorJena** [comment]
Still video is not playing.


![image](https://user-images.githubusercontent.com/19212755/191339542-68dedf2d-d477-4ba1-9f73-d3bd1ee1e419.png)

**Comment by piroposantosdev** [comment]
Sorry, this video link is not available anymore... try this https://www.w3schools.com/html/mov_bbb.mp4

> Still video is not playing.
> 
> ![image](https://user-images.githubusercontent.com/19212755/191339542-68dedf2d-d477-4ba1-9f73-d3bd1ee1e419.png)

**Comment by KishorJena** [comment]
dont know where it is but i get this log on console
```isFull == undefined``` 
although I did not print this log by myself.

**Comment by piroposantosdev** [comment]
> dont know where it is but i get this log on console `isFull == undefined` although I did not print this log by myself.

try this...

`<VlCPlayerView autoplay={true} url="https://www.w3schools.com/html/mov_bbb.mp4" ggUrl="" showGG={true} showTitle={true} title="Big Buck Bunny" showBack={true} onLeftPress={()=>{}} />`

**Comment by KishorJena** [comment]
what is ggurl. 
I set it showGG as false assuming it related to ggurl. 
It shows error on player View component along with 3 buttons.

![image](https://user-images.githubusercontent.com/19212755/191341789-04f92496-042b-473c-a499-311586b72df8.png)
![image](https://user-images.githubusercontent.com/19212755/191341878-2fe6c18b-17df-411d-b637-057d375db786.png)

**Comment by piroposantosdev** [comment]
did you remove the "space" i wrongly put in the url? you don't need GGURL, i'll remove it, because this is something from slider component that was removed

**Comment by KishorJena** [comment]
```bash
 isFull == undefined
 LOG  _onLoadStart
 LOG  {}
 LOG  onOpen {"currentTime": 0, "duration": 0, "isPlaying": false, "position": 0, "type": "Opening"}
 LOG  onBuffering
 LOG  {"bufferRate": 0, "currentTime": 0, "duration": 0, "isPlaying": false, "position": 0, "type": "Buffering"}
 LOG  _onError
 LOG  {"currentTime": 0, "duration": 0, "isPlaying": false, "position": 0, "type": "Error"}
 LOG  onEnded ---------->
 LOG  undefined
 LOG  <---------- onEnded
 LOG  bufferIntervalFunction
 LOG  bufferIntervalFunction
 LOG  bufferIntervalFunction
 LOG  bufferIntervalFunction
 LOG  remove  bufferIntervalFunctio
```

**Comment by KishorJena** [comment]
> did you remove the "space" i wrongly put in the url? you don't need GGURL, i'll remove it, because this is something from slider component that was removed

No. I used as it is just tried toggling the showgg()
Btw can we play local video?

**Comment by piroposantosdev** [comment]
yes you can play local videos, but it's working now?

**Comment by KishorJena** [comment]
No still not playing.. isPLaying:false

> try just this, and let me know what happens
> 
> `<VlCPlayerView autoplay={true} url="https://www.w3schools.com/html/mov_bbb.mp4" showTitle={true} title="Big Buck Bunny" showBack={true} onLeftPress={()=>{}} />`

wow ut worked

> try just this, and let me know what happens
> 
> `<VlCPlayerView autoplay={true} url="https://www.w3schools.com/html/mov_bbb.mp4" showTitle={true} title="Big Buck Bunny" showBack={true} onLeftPress={()=>{}} />`

Damn it worked. I had

> try just this, and let me know what happens
> 
> `<VlCPlayerView autoplay={true} url="https://www.w3schools.com/html/mov_bbb.mp4" showTitle={true} title="Big Buck Bunny" showBack={true} onLeftPress={()=>{}} />`

wow it worked

**Comment by piroposantosdev** [comment]
please, post your VlCPlayerView code here

**Comment by KishorJena** [comment]
```js
import {VLCPlayer, VlCPlayerView} from 'react-native-vlc-media-player';
import Orientation from 'react-native-orientation';
import RNFS from 'react-native-fs'

const log = console.log;

// log(RNFS.DownloadDirectoryPath+'/sample1.mkv')

const App = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  const url = "https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4"

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
    
         <VlCPlayerView 
            autoplay={false}
            url={RNFS.DownloadDirectoryPath+'/sample1.mkv'} 
            Orientation={Orientation} 
            // ggUrl="" 
            // showGG={false} 
            showTitle={true} 
            title="Big Buck Bunny" 
            showBack={true} 
            onLeftPress={()=>{
              log('left pressed')
            }}
            onBuffering={()=>{log('bufferring...')}}
            onEnded={()=>{log('onEnded...')}}
            onStopped={()=>{log('stopped...')}}
            onPaused={()=>{log('onPaused...')}}
            onError={(x)=>{log('onError...',x)}}
            />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};
```

also tried  autoplay={true}

but we are getting error I think

```
onOpen {"currentTime": 0, "duration": 0, "isPlaying": false, "position": 0, "type": "Opening"}
 LOG  onBuffering
 LOG  {"bufferRate": 0, "currentTime": 0, "duration": 0, "isPlaying": false, "position": 0, "type": "Buffering"}
 LOG  _onError
 LOG  {"currentTime": 0, "duration": 0, "isPlaying": false, "position": 0, "type": "Error"}
```

**Comment by piroposantosdev** [comment]
try just this, and let me know what happens

`<VlCPlayerView autoplay={true} url="https://www.w3schools.com/html/mov_bbb.mp4" showTitle={true} title="Big Buck Bunny" showBack={true} onLeftPress={()=>{}} />`

**Comment by KishorJena** [comment]
Yes it worked

**Comment by KishorJena** [comment]
The first video url has some isseu it seems

**Comment by piroposantosdev** [comment]
> The first video url has some isseu it seems

ok, so you need to check your video link to see what is happening, because VLC Player is working normally

**Comment by KishorJena** [comment]
> use this... `<VlCPlayerView autoplay={false} url="https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4" Orientation={Orientation} ggUrl="" showGG={true} showTitle={true} title="Big Buck Bunny" showBack={true} onLeftPress={()=>{}} />`
> 
> VLCPlayer is just for simple usage, there is no configurations for it

There was two isseues in this snippet. shoGG={true} and the broken link of video. now working fine.
What is gg here?

**Comment by piroposantosdev** [comment]
> > use this... `<VlCPlayerView autoplay={false} url="https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4" Orientation={Orientation} ggUrl="" showGG={true} showTitle={true} title="Big Buck Bunny" showBack={true} onLeftPress={()=>{}} />`
> > VLCPlayer is just for simple usage, there is no configurations for it
> 
> There was two isseues in this snippet. shoGG={true} and the broken link of video. now working fine. What is gg here?

As i said, GG is some function from previous VLC plugin that is vinculated to slider component that was removed... I'll update code removing this GG part. You don't need to use this.

**Comment by KishorJena** [comment]
Thank you. Actually I have to use vlc anyhow to demonstrate.  
Btw I could not play local mkv and mp4 file. 
Although I tried another video link (https://media.geeksforgeeks.org/wp-content/uploads/20190616234019/Canvas.move_.mp4) and it was being played.

**Comment by piroposantosdev** [comment]
MP4 and MKV are supported... you need to check if your link is usable correctly
