### ISSUE TITLE
Duplication in package.json causing error while installing

### ISSUE THREAD

**Issue by KishorJena** [piroposantosdev/react-native-vlc-player#5]
https://github.com/piroposantosdev/react-native-vlc-player/blob/3f6807b49de0c0a986b98572fc6bb9fb0dea0f5c/package.json#L36

**Comment by piroposantosdev** [comment]
try just deleting all duplicate fields

**Comment by KishorJena** [comment]
Actually I was clean installing. So am unable to download by npm i command. 
Btw I have sent PR

**Comment by piroposantosdev** [comment]
try now

**Comment by KishorJena** [comment]
> try now

solved 👍
